# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('time', models.TimeField()),
                ('league', models.TextField(max_length=100)),
                ('home_team', models.TextField(max_length=100)),
                ('away_team', models.TextField(max_length=100)),
                ('home_team_goals', models.IntegerField(default=None)),
                ('away_team_goals', models.IntegerField(default=None)),
                ('penalties', models.BooleanField(default=False)),
                ('home_penalty_goals', models.IntegerField(default=None)),
                ('away_penalty_goals', models.IntegerField(default=None)),
            ],
        ),
    ]
